### ISSUE TITLE
Support for configuration tag in plugin's execution tag.

### ISSUE THREAD

**Issue by Gautham-JS** [vifraa/gopom#10]
Hi there!,

While using this project for parsing one of my projects, I stumbled upon a problem involving parsing the "configuration" tag in the execution tag of a plugin. The tag I'm referencing is : 

>build > plugins > plugin > executions > execution > **configuration**

In my case I'm specifically using execution configurations with the maven-dependency-plugin. Which looks something like : 
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-dependency-plugin</artifactId>
    <version>3.1.1</version>
    <executions>
        <execution>
            <id>copy-artifact</id>
            <phase>package</phase>
            <goals>
                <goal>copy</goal>
            </goals>
            <!-- VVVV This tag is omitted on parse -->
            <configuration>
                <artifactItems>
                    <artifactItem>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>${project.artifactId}</artifactId>
                        <version>${project.version}</version>
                        <type>jar</type>
                        <destFileName>${outputname}</destFileName>
                    </artifactItem>
                </artifactItems>
                <outputDirectory>./jars/</outputDirectory>
            </configuration>
            <!-- ^^^ Till here -->
        </execution>
    </executions>
</plugin>
```

Can add a PR with the existing map based struct member for configurations added to `PluginExecution` struct. Similar to what I see is added to `Plugin` struct. Wanted to confirm if this is an issue beforehand.

**Comment by vifraa** [comment]
@Gautham-JS Which version are you running? The `PluginExecution` struct has the `Configuration` field you are looking for already. It was added in version [v0.2.2](https://github.com/vifraa/gopom/releases/tag/v0.2.2), so if you upgrade to that version or newer you should be good to go.

**Comment by Gautham-JS** [comment]
Hi there, my bad, I was running version 0.1.2 which is why I was not seeing that execution tag in my code. Apologies for the confusion.
Closing this issue.
